### ISSUE TITLE
Docker image build failed in VS code

### ISSUE THREAD

**Issue by Frank1016** [edwardinubuntu/flutter-web-dockerfile#3]
Hi, I downloaded this sample file and tried building it in VS code, but met this error:
<img width="897" alt="Screenshot 2023-01-17 at 11 32 58 AM" src="https://user-images.githubusercontent.com/32797520/212957060-f5d3fa15-dbfc-49e8-8b04-79751f14e0f7.png">

**Comment by edwardinubuntu** [comment]
I have a Windows 10 and a MacBook Pro 2021 M1 Chip. I got the same problem couldn't find any package by regex lib32stdc+6 on my Mac M1 chip, but build successful on my Windows 10. This is platform architecture amd64 issued.

I try several hours still looking for solution to build on M1 Chip, I will schedule time to look on this. In addition you can also find other windows, linux or other Mac not M1 Chip to run with. If you have any progress, very welcome to share your experince here.

**Comment by Frank1016** [comment]
> 

Yes, you are right! I have tried building you sample container on my PC with Windows 11, everything works perfectly! If you find the solution to build this also successfully on Mac M1, please do share here! Thank you in advance!

**Comment by kkalisz** [comment]
@Frank1016 you can just add --platform=linux/amd64 to your build command on mac

Edit: It will compile.. but indeed you may not be able to run it on Mac

**Comment by JesusHdez960717** [comment]
In fact, you can remove that package that gives an error and the app will compile, the only ones necessary are: curl, git and unzip.
The final line would be: `RUN apt-get install -y curl git unzip`

**Comment by edwardinubuntu** [comment]
Thanks for @JesusHdez960717 advise, the solution https://github.com/edwardinubuntu/flutter-web-dockerfile/issues/4 works nice, I have commit to the master branch.
