### ISSUE TITLE
This solution is amazing, but it can improve

### ISSUE THREAD

**Issue by JesusHdez960717** [edwardinubuntu/flutter-web-dockerfile#4]
After trying different ways to compile in the shortest possible time and as structured as possible, I arrived at this final solution for the dockerfile, which I currently have running wonderful  on the servers:
```
# Environemnt to install flutter and build web
FROM debian:latest AS build-env

#install all needed stuff
RUN apt-get update
RUN apt-get install -y curl git unzip

#define variables
ARG FLUTTER_SDK=/usr/local/flutter
ARG APP=/app/

#clone flutter
RUN git clone https://github.com/flutter/flutter.git $FLUTTER_SDK
#change dir to current flutter folder and make a checkout to the specific version
RUN cd $FLUTTER_SDK && git checkout efbf63d9c66b9f6ec30e9ad4611189aa80003d31

#setup the flutter path as an enviromental variable
ENV PATH="$FLUTTER_SDK/bin:$FLUTTER_SDK/bin/cache/dart-sdk/bin:${PATH}"

#Start to run Flutter commands
#doctor to see if all was installes ok
RUN flutter doctor -v

#create folder to copy source code
RUN mkdir $APP
#copy source code to folder
COPY . $APP
#stup new folder as the working directory
WORKDIR $APP

#Run build: 1 - clean, 2 - pub get, 3 - build web
RUN flutter clean
RUN flutter pub get
RUN flutter build web

#once heare the app will be compiled and ready to deploy

#use nginx to deploy
FROM nginx:1.25.2-alpine

#copy the info of the builded web app to nginx
COPY --from=build-env /app/build/web /usr/share/nginx/html

#Expose and run nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

In the line `RUN cd $FLUTTER_SDK && git checkout efbf63d9c66b9f6ec30e9ad4611189aa80003d31`, we can go to the flutter committee/version we want, in this case, version 3.13.0 named: `[flutter_releases] Flutter stable 3.13.0 Framework Cherrypicks (# 132610)`, has as a hash: "efbf63d9c66b9f6ec30e9ad4611189aa80003d31", and therefore the checkout is made to that specific committee/version.

Hope this help someone :+1:

**Comment by edwardinubuntu** [comment]
Thanks @JesusHdez960717 the solution works.

**Comment by JesusHdez960717** [comment]
Please note that in line 15 the checkout is at version 3.13.0, and maybe in a future another version need to be used, so maybe in the readme should have an explanation on how to change the checkout to the desired version.

**Comment by edwardinubuntu** [comment]
Thanks, have updated

**Comment by JesusHdez960717** [comment]
Perfection 👌👌👌
Thanks
